
ALTER TABLE wereldeconomie
ADD COLUMN id INT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE landen
MODIFY Country_Code VARCHAR(255) PRIMARY KEY;

ALTER TABLE indicatoren
MODIFY INDICATOR_CODE VARCHAR(255) PRIMARY KEY;

ALTER TABLE wereldeconomie
ADD CONSTRAINT fk_cc
FOREIGN KEY(Country_Code) REFERENCES landen(Country_Code);

ALTER TABLE wereldeconomie
ADD CONSTRAINT fk
FOREIGN KEY(Indicator_Code) REFERENCES indicatoren(INDICATOR_CODE);